import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../domain/entities/insurance_assistant_models.dart';

/// Builds the portable conversation document without depending on Flutter.
///
/// Keeping the document layout here lets us test the generated bytes and
/// visually inspect the exact PDF that users receive.
class InsuranceConversationPdfBuilder {
  const InsuranceConversationPdfBuilder._();

  static Future<Uint8List> build({
    required List<InsuranceChatMessage> messages,
    required pw.Font regularFont,
    required pw.Font boldFont,
    required pw.Font arabicFont,
    String? title,
  }) async {
    if (messages.isEmpty) {
      throw StateError('There are no messages to export.');
    }

    final document = pw.Document(
      title: title ?? 'Insurance conversation',
      author: 'Insurance Knowledge Assistant',
      theme: pw.ThemeData.withFont(
        base: regularFont,
        bold: boldFont,
        fontFallback: [arabicFont],
      ),
    );

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(34),
        build: (_) => [for (final message in messages) _messageBlock(message)],
      ),
    );
    return document.save();
  }

  static pw.Widget _messageBlock(InsuranceChatMessage message) {
    final isQuestion = message.isUser;
    final value = _plainText(
      isQuestion ? message.message : _answerOnly(message.message),
    );
    final direction = _containsArabic(value)
        ? pw.TextDirection.rtl
        : pw.TextDirection.ltr;

    return pw.Container(
      width: double.infinity,
      margin: const pw.EdgeInsets.only(bottom: 14),
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: isQuestion ? PdfColors.indigo50 : PdfColors.white,
        borderRadius: pw.BorderRadius.circular(10),
        border: pw.Border.all(
          color: isQuestion ? PdfColors.indigo200 : PdfColors.blueGrey200,
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            isQuestion ? 'QUESTION' : 'ANSWER',
            style: pw.TextStyle(
              fontSize: 8,
              fontWeight: pw.FontWeight.bold,
              color: isQuestion ? PdfColors.indigo700 : PdfColors.green700,
              letterSpacing: 1,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Directionality(
            textDirection: direction,
            child: pw.Text(
              value,
              textAlign: direction == pw.TextDirection.rtl
                  ? pw.TextAlign.right
                  : pw.TextAlign.left,
              style: const pw.TextStyle(
                fontSize: 11,
                height: 1.55,
                color: PdfColors.blueGrey900,
              ),
            ),
          ),
        ],
      ),
    );
  }

  static bool _containsArabic(String value) =>
      RegExp(r'[\u0600-\u06FF]').hasMatch(value);

  static String _plainText(String value) => value
      .replaceAll(RegExp(r'\*\*|__|`'), '')
      .replaceAll(RegExp(r'^#{1,6}\s+', multiLine: true), '')
      .replaceAll(RegExp(r'\n{3,}'), '\n\n')
      .trim();

  static String _answerOnly(String value) => value
      .replaceFirst(RegExp(r'\n+Source\s*\n[\s\S]*$', caseSensitive: false), '')
      .replaceFirst(RegExp(r'\n+المصدر\s*\n[\s\S]*$'), '')
      .trim();
}
