-- Items Tracker module
--
-- Run this migration once from the Supabase SQL editor. It is safe to rerun:
-- tables and indexes use IF NOT EXISTS, while functions, triggers, views, and
-- policies are replaced deterministically.
--
-- Important data rule: item_report.retail is saved only as retail_snapshot.
-- It is never treated as item cost. unit_cost_snapshot is an optional manual
-- Inventory input and required_value remains NULL when no unit cost is entered.

begin;

-- purchase_status_module.sql already removes this conventional constraint.
-- Repeating the operation here keeps standalone installations able to assign
-- the new app_users.role = 'category' value without guessing every legacy role.
alter table if exists public.app_users
  drop constraint if exists app_users_role_check;

create or replace function public.item_tracker_my_role()
returns text
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select lower(btrim(au.role::text))
  from public.app_users au
  where au.user_id = auth.uid()
    and au.is_active is not false
    and lower(btrim(au.role::text)) in ('inventory', 'purchase', 'category')
  limit 1;
$$;

create table if not exists public.items_tracker_items (
  id uuid primary key default gen_random_uuid(),
  escalated_date date not null
    default ((now() at time zone 'Asia/Dubai')::date),

  -- Immutable catalog snapshots captured when Inventory creates the case.
  item_code text not null,
  item_name text not null,
  category text,
  supplier text,
  company text,
  source_item_status text,
  retail_snapshot numeric(20, 4),

  -- Optional manual Inventory value. Retail is deliberately not a fallback.
  unit_cost_snapshot numeric(20, 4),
  unit_cost_source text,
  inventory_note text,
  required_qty numeric(20, 3) not null,
  required_value numeric(24, 2) generated always as (
    case
      when unit_cost_snapshot is null then null
      else round(unit_cost_snapshot * required_qty, 2)
    end
  ) stored,

  status_updated_to text not null,
  follow_up_role text not null,
  case_status text not null default 'pending',

  created_by uuid not null default auth.uid(),
  created_by_role text not null,
  created_at timestamptz not null default now(),
  updated_by uuid not null default auth.uid(),
  updated_by_role text not null,
  updated_at timestamptz not null default now(),
  row_version bigint not null default 1,
  closed_at timestamptz,
  closed_by uuid,

  constraint items_tracker_items_code_not_blank
    check (btrim(item_code) <> ''),
  constraint items_tracker_items_name_not_blank
    check (btrim(item_name) <> ''),
  constraint items_tracker_items_qty_positive
    check (required_qty > 0),
  constraint items_tracker_items_retail_nonnegative
    check (retail_snapshot is null or retail_snapshot >= 0),
  constraint items_tracker_items_cost_nonnegative
    check (unit_cost_snapshot is null or unit_cost_snapshot >= 0),
  constraint items_tracker_items_cost_source_consistent
    check (
      (unit_cost_snapshot is null and unit_cost_source is null)
      or
      (unit_cost_snapshot is not null and btrim(coalesce(unit_cost_source, '')) <> '')
    ),
  constraint items_tracker_items_status_updated_not_blank
    check (btrim(status_updated_to) <> ''),
  constraint items_tracker_items_follow_up_role_check
    check (follow_up_role in ('inventory', 'purchase', 'category')),
  constraint items_tracker_items_case_status_check
    check (case_status in ('pending', 'done')),
  constraint items_tracker_items_created_role_check
    check (created_by_role in ('inventory', 'purchase', 'category')),
  constraint items_tracker_items_updated_role_check
    check (updated_by_role in ('inventory', 'purchase', 'category'))
);

create table if not exists public.items_tracker_events (
  id bigint generated by default as identity primary key,
  item_id uuid not null
    references public.items_tracker_items(id) on delete restrict,
  event_type text not null,
  action_date date,
  body text,
  from_follow_up_role text,
  to_follow_up_role text,
  from_case_status text,
  to_case_status text,
  details jsonb not null default '{}'::jsonb,
  actor_id uuid not null default auth.uid(),
  actor_role text not null,
  created_at timestamptz not null default now(),

  constraint items_tracker_events_type_check
    check (
      event_type in (
        'created',
        'inventory_update',
        'action',
        'follow_up',
        'status_change',
        'file_uploaded'
      )
    ),
  constraint items_tracker_events_actor_role_check
    check (actor_role in ('inventory', 'purchase', 'category')),
  constraint items_tracker_events_from_follow_up_check
    check (
      from_follow_up_role is null
      or from_follow_up_role in ('inventory', 'purchase', 'category')
    ),
  constraint items_tracker_events_to_follow_up_check
    check (
      to_follow_up_role is null
      or to_follow_up_role in ('inventory', 'purchase', 'category')
    ),
  constraint items_tracker_events_from_status_check
    check (
      from_case_status is null
      or from_case_status in ('pending', 'done')
    ),
  constraint items_tracker_events_to_status_check
    check (
      to_case_status is null
      or to_case_status in ('pending', 'done')
    ),
  constraint items_tracker_events_action_body_check
    check (
      event_type <> 'action'
      or btrim(coalesce(body, '')) <> ''
    ),
  constraint items_tracker_events_follow_up_target_check
    check (
      event_type not in ('created', 'follow_up')
      or to_follow_up_role is not null
    )
);

-- Tracker Status is intentionally a simple Inventory-owned two-state field.
-- Normalize data created by earlier module versions before tightening checks.
alter table public.items_tracker_items
  drop constraint if exists items_tracker_items_case_status_check;
alter table public.items_tracker_events
  drop constraint if exists items_tracker_events_from_status_check;
alter table public.items_tracker_events
  drop constraint if exists items_tracker_events_to_status_check;

update public.items_tracker_items
set case_status = case
  when case_status in ('resolved', 'closed', 'done') then 'done'
  else 'pending'
end
where case_status not in ('pending', 'done');

update public.items_tracker_events
set
  from_case_status = case
    when from_case_status in ('resolved', 'closed', 'done') then 'done'
    when from_case_status is null then null
    else 'pending'
  end,
  to_case_status = case
    when to_case_status in ('resolved', 'closed', 'done') then 'done'
    when to_case_status is null then null
    else 'pending'
  end
where from_case_status not in ('pending', 'done')
   or to_case_status not in ('pending', 'done');

alter table public.items_tracker_items
  add constraint items_tracker_items_case_status_check
  check (case_status in ('pending', 'done'));
alter table public.items_tracker_events
  add constraint items_tracker_events_from_status_check
  check (from_case_status is null or from_case_status in ('pending', 'done'));
alter table public.items_tracker_events
  add constraint items_tracker_events_to_status_check
  check (to_case_status is null or to_case_status in ('pending', 'done'));

-- Keep reruns compatible with the first Items Tracker release, whose event
-- constraint did not yet include secure file-upload history entries.
alter table public.items_tracker_events
  drop constraint if exists items_tracker_events_type_check;
alter table public.items_tracker_events
  add constraint items_tracker_events_type_check
  check (
    event_type in (
      'created',
      'inventory_update',
      'action',
      'follow_up',
      'status_change',
      'file_uploaded'
    )
  );

create table if not exists public.items_tracker_comments (
  id bigint generated by default as identity primary key,
  item_id uuid not null
    references public.items_tracker_items(id) on delete restrict,
  body text not null,
  created_by uuid not null default auth.uid(),
  created_by_role text not null,
  created_at timestamptz not null default now(),

  constraint items_tracker_comments_body_not_blank
    check (btrim(body) <> ''),
  constraint items_tracker_comments_role_check
    check (created_by_role in ('inventory', 'purchase', 'category'))
);

create table if not exists public.items_tracker_attachments (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null
    references public.items_tracker_items(id) on delete restrict,
  event_id bigint not null unique
    references public.items_tracker_events(id) on delete restrict,
  activity_event_id bigint
    references public.items_tracker_events(id) on delete restrict,
  bucket_name text not null default 'items-tracker-files',
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  file_size bigint not null,
  created_by uuid not null default auth.uid(),
  created_by_role text not null,
  created_at timestamptz not null default now(),

  constraint items_tracker_attachments_bucket_check
    check (bucket_name = 'items-tracker-files'),
  constraint items_tracker_attachments_path_not_blank
    check (btrim(storage_path) <> ''),
  constraint items_tracker_attachments_name_not_blank
    check (btrim(file_name) <> ''),
  constraint items_tracker_attachments_mime_check
    check (
      mime_type in (
        'application/pdf',
        'image/jpeg',
        'image/png',
        'image/webp'
      )
    ),
  constraint items_tracker_attachments_size_check
    check (file_size > 0 and file_size <= 15728640),
  constraint items_tracker_attachments_role_check
    check (created_by_role in ('inventory', 'purchase', 'category'))
);

alter table public.items_tracker_attachments
  add column if not exists activity_event_id bigint
    references public.items_tracker_events(id) on delete restrict;

-- Backfill files created by an earlier version of this module by linking each
-- upload to the nearest preceding Action/Follow-up from the same user.
update public.items_tracker_attachments a
set activity_event_id = (
  select e.id
  from public.items_tracker_events e
  where e.item_id = a.item_id
    and e.event_type in ('action', 'follow_up')
    and e.actor_id = a.created_by
    and e.created_at <= a.created_at
  order by e.created_at desc, e.id desc
  limit 1
)
where a.activity_event_id is null;

create index if not exists items_tracker_items_assignment_idx
  on public.items_tracker_items (
    follow_up_role,
    case_status,
    updated_at desc,
    id
  );

create index if not exists items_tracker_items_item_code_idx
  on public.items_tracker_items (lower(btrim(item_code)));

create index if not exists items_tracker_items_item_name_idx
  on public.items_tracker_items (lower(btrim(item_name)));

create index if not exists items_tracker_items_escalated_date_idx
  on public.items_tracker_items (escalated_date desc, id);

create index if not exists items_tracker_events_item_created_idx
  on public.items_tracker_events (item_id, created_at desc, id desc);

create index if not exists items_tracker_events_last_action_idx
  on public.items_tracker_events (item_id, created_at desc, id desc)
  where event_type = 'action';

create index if not exists items_tracker_events_last_follow_up_idx
  on public.items_tracker_events (item_id, created_at desc, id desc)
  where event_type in ('created', 'follow_up');

create index if not exists items_tracker_comments_item_created_idx
  on public.items_tracker_comments (item_id, created_at desc, id desc);

create index if not exists items_tracker_attachments_item_created_idx
  on public.items_tracker_attachments (item_id, created_at desc, id desc);
create index if not exists items_tracker_attachments_activity_event_idx
  on public.items_tracker_attachments (activity_event_id, created_at desc);

-- Private bucket: files are never public. The app opens them with short-lived
-- signed URLs after the user passes Items Tracker role checks.
insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
) values (
  'items-tracker-files',
  'items-tracker-files',
  false,
  15728640,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp'
  ]::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create or replace function public.items_tracker_touch_item()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at := now();
  new.row_version := old.row_version + 1;
  return new;
end;
$$;

drop trigger if exists items_tracker_touch_item_trigger
  on public.items_tracker_items;
create trigger items_tracker_touch_item_trigger
before update on public.items_tracker_items
for each row execute function public.items_tracker_touch_item();

-- Catalog autocomplete. All returned values are catalog values; no client
-- supplied snapshot is trusted by items_tracker_create().
create or replace function public.item_tracker_search_catalog(
  p_query text,
  p_limit integer default 15
)
returns table (
  item_code text,
  item_name text,
  category text,
  supplier text,
  company text,
  item_status text,
  retail numeric
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_query text := btrim(coalesce(p_query, ''));
  v_limit integer := least(greatest(coalesce(p_limit, 15), 1), 50);
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  if v_query = '' then
    return;
  end if;

  return query
  select
    ir.item_code::text,
    ir.item_name::text,
    ir.category::text,
    ir.supplier::text,
    ir.company::text,
    ir.item_status::text,
    ir.retail::numeric
  from public.item_report ir
  where ir.item_code::text ilike ('%' || v_query || '%')
     or ir.item_name::text ilike ('%' || v_query || '%')
  order by
    case
      when lower(btrim(ir.item_code::text)) = lower(v_query) then 0
      when lower(btrim(ir.item_name::text)) = lower(v_query) then 1
      when lower(ir.item_code::text) like lower(v_query) || '%' then 2
      else 3
    end,
    ir.item_name::text,
    ir.item_code::text
  limit v_limit;
end;
$$;

create or replace function public.item_tracker_status_options()
returns table (item_status text)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  return query
  select distinct btrim(ir.item_status::text)
  from public.item_report ir
  where nullif(btrim(ir.item_status::text), '') is not null
  order by 1;
end;
$$;

create or replace function public.item_tracker_create(
  p_escalated_date date,
  p_item_code text,
  p_unit_cost numeric,
  p_inventory_note text,
  p_required_qty numeric,
  p_status_updated_to text,
  p_follow_up_role text
)
returns public.items_tracker_items
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_catalog record;
  v_status_updated_to text;
  v_follow_up_role text;
  v_item public.items_tracker_items%rowtype;
begin
  if v_role is distinct from 'inventory' then
    raise exception 'INVENTORY_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  if nullif(btrim(coalesce(p_item_code, '')), '') is null then
    raise exception 'ITEM_CODE_REQUIRED' using errcode = '22023';
  end if;

  if p_required_qty is null or p_required_qty <= 0 then
    raise exception 'REQUIRED_QUANTITY_MUST_BE_POSITIVE'
      using errcode = '22023';
  end if;

  if p_unit_cost is not null and p_unit_cost < 0 then
    raise exception 'UNIT_COST_CANNOT_BE_NEGATIVE'
      using errcode = '22023';
  end if;

  select
    nullif(btrim(ir.item_code::text), '') as item_code,
    nullif(btrim(ir.item_name::text), '') as item_name,
    nullif(btrim(ir.category::text), '') as category,
    nullif(btrim(ir.supplier::text), '') as supplier,
    nullif(btrim(ir.company::text), '') as company,
    nullif(btrim(ir.item_status::text), '') as item_status,
    ir.retail::numeric as retail
  into v_catalog
  from public.item_report ir
  where lower(btrim(ir.item_code::text)) =
    lower(btrim(p_item_code))
  limit 1;

  if not found or v_catalog.item_name is null then
    raise exception 'ITEM_NOT_FOUND_IN_ITEM_REPORT'
      using errcode = 'P0002';
  end if;

  if nullif(btrim(coalesce(p_status_updated_to, '')), '') is null then
    raise exception 'STATUS_UPDATED_TO_REQUIRED'
      using errcode = '22023';
  end if;

  select btrim(ir.item_status::text)
  into v_status_updated_to
  from public.item_report ir
  where lower(btrim(ir.item_status::text)) =
    lower(btrim(p_status_updated_to))
  order by ir.item_status::text
  limit 1;

  if not found or v_status_updated_to is null then
    raise exception 'INVALID_ITEM_STATUS'
      using errcode = '22023';
  end if;

  v_follow_up_role := lower(btrim(coalesce(p_follow_up_role, '')));
  if v_follow_up_role = '' then
    v_follow_up_role := case
      when upper(btrim(coalesce(v_catalog.category, ''))) = 'MEDICINE'
        then 'purchase'
      else 'category'
    end;
  end if;

  if v_follow_up_role not in ('inventory', 'purchase', 'category') then
    raise exception 'INVALID_FOLLOW_UP_ROLE'
      using errcode = '22023';
  end if;

  insert into public.items_tracker_items (
    escalated_date,
    item_code,
    item_name,
    category,
    supplier,
    company,
    source_item_status,
    retail_snapshot,
    unit_cost_snapshot,
    unit_cost_source,
    inventory_note,
    required_qty,
    status_updated_to,
    follow_up_role,
    case_status,
    created_by,
    created_by_role,
    updated_by,
    updated_by_role
  ) values (
    coalesce(
      p_escalated_date,
      (now() at time zone 'Asia/Dubai')::date
    ),
    v_catalog.item_code,
    v_catalog.item_name,
    v_catalog.category,
    v_catalog.supplier,
    v_catalog.company,
    v_catalog.item_status,
    v_catalog.retail,
    p_unit_cost,
    case
      when p_unit_cost is null then null
      else 'manual_inventory'
    end,
    nullif(btrim(coalesce(p_inventory_note, '')), ''),
    p_required_qty,
    v_status_updated_to,
    v_follow_up_role,
    'pending',
    auth.uid(),
    v_role,
    auth.uid(),
    v_role
  )
  returning * into v_item;

  insert into public.items_tracker_events (
    item_id,
    event_type,
    action_date,
    body,
    to_follow_up_role,
    to_case_status,
    details,
    actor_id,
    actor_role
  ) values (
    v_item.id,
    'created',
    v_item.escalated_date,
    'Item escalated by Inventory',
    v_item.follow_up_role,
    v_item.case_status,
    jsonb_build_object(
      'escalated_date', v_item.escalated_date,
      'item_code', v_item.item_code,
      'required_qty', v_item.required_qty,
      'unit_cost_snapshot', v_item.unit_cost_snapshot,
      'required_value', v_item.required_value,
      'status_updated_to', v_item.status_updated_to
    ),
    auth.uid(),
    v_role
  );

  return v_item;
end;
$$;

create or replace function public.item_tracker_update_inventory_fields(
  p_item_id uuid,
  p_escalated_date date,
  p_unit_cost numeric,
  p_inventory_note text,
  p_required_qty numeric,
  p_status_updated_to text,
  p_follow_up_role text,
  p_expected_version bigint
)
returns public.items_tracker_items
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_old public.items_tracker_items%rowtype;
  v_new public.items_tracker_items%rowtype;
  v_status_updated_to text;
  v_follow_up_role text;
begin
  if v_role is distinct from 'inventory' then
    raise exception 'INVENTORY_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  select * into v_old
  from public.items_tracker_items
  where id = p_item_id
  for update;

  if not found then
    raise exception 'ITEMS_TRACKER_ITEM_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  if p_expected_version is not null
    and v_old.row_version is distinct from p_expected_version then
    raise exception 'STALE_ITEM_VERSION'
      using errcode = '40001';
  end if;

  if p_escalated_date is null then
    raise exception 'ESCALATED_DATE_REQUIRED' using errcode = '22023';
  end if;

  if p_required_qty is null or p_required_qty <= 0 then
    raise exception 'REQUIRED_QUANTITY_MUST_BE_POSITIVE'
      using errcode = '22023';
  end if;

  if p_unit_cost is not null and p_unit_cost < 0 then
    raise exception 'UNIT_COST_CANNOT_BE_NEGATIVE'
      using errcode = '22023';
  end if;

  if nullif(btrim(coalesce(p_status_updated_to, '')), '') is null then
    raise exception 'STATUS_UPDATED_TO_REQUIRED'
      using errcode = '22023';
  end if;

  select btrim(ir.item_status::text)
  into v_status_updated_to
  from public.item_report ir
  where lower(btrim(ir.item_status::text)) =
    lower(btrim(p_status_updated_to))
  order by ir.item_status::text
  limit 1;

  if not found or v_status_updated_to is null then
    raise exception 'INVALID_ITEM_STATUS'
      using errcode = '22023';
  end if;

  v_follow_up_role := lower(
    btrim(coalesce(p_follow_up_role, v_old.follow_up_role, ''))
  );
  if v_follow_up_role not in ('inventory', 'purchase', 'category') then
    raise exception 'INVALID_FOLLOW_UP_ROLE'
      using errcode = '22023';
  end if;

  update public.items_tracker_items
  set
    escalated_date = p_escalated_date,
    required_qty = p_required_qty,
    inventory_note = nullif(btrim(coalesce(p_inventory_note, '')), ''),
    status_updated_to = v_status_updated_to,
    unit_cost_snapshot = p_unit_cost,
    unit_cost_source = case
      when p_unit_cost is null then null
      else 'manual_inventory'
    end,
    follow_up_role = v_follow_up_role,
    updated_by = auth.uid(),
    updated_by_role = v_role
  where id = p_item_id
  returning * into v_new;

  insert into public.items_tracker_events (
    item_id,
    event_type,
    body,
    details,
    actor_id,
    actor_role
  ) values (
    p_item_id,
    'inventory_update',
    'Inventory fields updated',
    jsonb_build_object(
      'old', jsonb_build_object(
        'escalated_date', v_old.escalated_date,
        'required_qty', v_old.required_qty,
        'inventory_note', v_old.inventory_note,
        'status_updated_to', v_old.status_updated_to,
        'follow_up_role', v_old.follow_up_role,
        'unit_cost_snapshot', v_old.unit_cost_snapshot,
        'required_value', v_old.required_value
      ),
      'new', jsonb_build_object(
        'escalated_date', v_new.escalated_date,
        'required_qty', v_new.required_qty,
        'inventory_note', v_new.inventory_note,
        'status_updated_to', v_new.status_updated_to,
        'follow_up_role', v_new.follow_up_role,
        'unit_cost_snapshot', v_new.unit_cost_snapshot,
        'required_value', v_new.required_value
      )
    ),
    auth.uid(),
    v_role
  );

  if v_old.follow_up_role is distinct from v_new.follow_up_role then
    insert into public.items_tracker_events (
      item_id,
      event_type,
      action_date,
      body,
      from_follow_up_role,
      to_follow_up_role,
      from_case_status,
      to_case_status,
      actor_id,
      actor_role
    ) values (
      p_item_id,
      'follow_up',
      (now() at time zone 'Asia/Dubai')::date,
      'Follow-up changed by Inventory',
      v_old.follow_up_role,
      v_new.follow_up_role,
      v_old.case_status,
      v_new.case_status,
      auth.uid(),
      v_role
    );
  end if;

  return v_new;
end;
$$;

create or replace function public.item_tracker_change_follow_up(
  p_item_id uuid,
  p_target_role text,
  p_note text,
  p_action_date date,
  p_expected_version bigint
)
returns public.items_tracker_items
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_target_role text := lower(btrim(coalesce(p_target_role, '')));
  v_old public.items_tracker_items%rowtype;
  v_new public.items_tracker_items%rowtype;
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  if v_target_role not in ('inventory', 'purchase', 'category') then
    raise exception 'INVALID_FOLLOW_UP_ROLE'
      using errcode = '22023';
  end if;

  select * into v_old
  from public.items_tracker_items
  where id = p_item_id
  for update;

  if not found then
    raise exception 'ITEMS_TRACKER_ITEM_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  if p_expected_version is not null
    and v_old.row_version is distinct from p_expected_version then
    raise exception 'STALE_ITEM_VERSION'
      using errcode = '40001';
  end if;

  if v_old.follow_up_role is distinct from v_role then
    raise exception 'ITEM_IS_NOT_ASSIGNED_TO_YOUR_ROLE'
      using errcode = '42501';
  end if;

  update public.items_tracker_items
  set
    follow_up_role = v_target_role,
    updated_by = auth.uid(),
    updated_by_role = v_role
  where id = p_item_id
  returning * into v_new;

  insert into public.items_tracker_events (
    item_id,
    event_type,
    action_date,
    body,
    from_follow_up_role,
    to_follow_up_role,
    from_case_status,
    to_case_status,
    actor_id,
    actor_role
  ) values (
    p_item_id,
    'follow_up',
    coalesce(
      p_action_date,
      (now() at time zone 'Asia/Dubai')::date
    ),
    nullif(btrim(coalesce(p_note, '')), ''),
    v_old.follow_up_role,
    v_new.follow_up_role,
    v_old.case_status,
    v_new.case_status,
    auth.uid(),
    v_role
  );

  return v_new;
end;
$$;

create or replace function public.item_tracker_update_tracker_status(
  p_item_id uuid,
  p_tracker_status text,
  p_expected_version bigint
)
returns public.items_tracker_items
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_old public.items_tracker_items%rowtype;
  v_new public.items_tracker_items%rowtype;
  v_status text := lower(btrim(coalesce(p_tracker_status, '')));
begin
  if v_role is distinct from 'inventory' then
    raise exception 'INVENTORY_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  if v_status not in ('pending', 'done') then
    raise exception 'INVALID_TRACKER_STATUS' using errcode = '22023';
  end if;

  select * into v_old
  from public.items_tracker_items
  where id = p_item_id
  for update;

  if not found then
    raise exception 'ITEMS_TRACKER_ITEM_NOT_FOUND' using errcode = 'P0002';
  end if;

  if p_expected_version is not null
    and v_old.row_version is distinct from p_expected_version then
    raise exception 'STALE_ITEM_VERSION' using errcode = '40001';
  end if;

  if v_old.case_status = v_status then
    return v_old;
  end if;

  update public.items_tracker_items
  set
    case_status = v_status,
    closed_at = case when v_status = 'done' then now() else null end,
    closed_by = case when v_status = 'done' then auth.uid() else null end,
    updated_by = auth.uid(),
    updated_by_role = v_role
  where id = p_item_id
  returning * into v_new;

  insert into public.items_tracker_events (
    item_id,
    event_type,
    body,
    from_case_status,
    to_case_status,
    actor_id,
    actor_role
  ) values (
    p_item_id,
    'status_change',
    'Tracker Status changed from ' || initcap(v_old.case_status) ||
      ' to ' || initcap(v_status),
    v_old.case_status,
    v_status,
    auth.uid(),
    v_role
  );

  return v_new;
end;
$$;

create or replace function public.item_tracker_add_action(
  p_item_id uuid,
  p_action_date date,
  p_body text,
  p_case_status text,
  p_expected_version bigint
)
returns public.items_tracker_events
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_old public.items_tracker_items%rowtype;
  v_event public.items_tracker_events%rowtype;
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  if nullif(btrim(coalesce(p_body, '')), '') is null then
    raise exception 'ACTION_BODY_REQUIRED' using errcode = '22023';
  end if;

  select * into v_old
  from public.items_tracker_items
  where id = p_item_id
  for update;

  if not found then
    raise exception 'ITEMS_TRACKER_ITEM_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  if p_expected_version is not null
    and v_old.row_version is distinct from p_expected_version then
    raise exception 'STALE_ITEM_VERSION'
      using errcode = '40001';
  end if;

  if v_old.follow_up_role is distinct from v_role then
    raise exception 'ITEM_IS_NOT_ASSIGNED_TO_YOUR_ROLE'
      using errcode = '42501';
  end if;

  update public.items_tracker_items
  set
    updated_by = auth.uid(),
    updated_by_role = v_role
  where id = p_item_id;

  insert into public.items_tracker_events (
    item_id,
    event_type,
    action_date,
    body,
    from_follow_up_role,
    to_follow_up_role,
    from_case_status,
    to_case_status,
    actor_id,
    actor_role
  ) values (
    p_item_id,
    'action',
    coalesce(
      p_action_date,
      (now() at time zone 'Asia/Dubai')::date
    ),
    btrim(p_body),
    v_old.follow_up_role,
    v_old.follow_up_role,
    v_old.case_status,
    v_old.case_status,
    auth.uid(),
    v_role
  )
  returning * into v_event;

  return v_event;
end;
$$;

create or replace function public.item_tracker_add_comment(
  p_item_id uuid,
  p_body text
)
returns public.items_tracker_comments
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_comment public.items_tracker_comments%rowtype;
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  if nullif(btrim(coalesce(p_body, '')), '') is null then
    raise exception 'COMMENT_BODY_REQUIRED' using errcode = '22023';
  end if;

  perform 1
  from public.items_tracker_items
  where id = p_item_id;

  if not found then
    raise exception 'ITEMS_TRACKER_ITEM_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  insert into public.items_tracker_comments (
    item_id,
    body,
    created_by,
    created_by_role
  ) values (
    p_item_id,
    btrim(p_body),
    auth.uid(),
    v_role
  )
  returning * into v_comment;

  -- Keep the main grid ordered by any recent collaboration, including comments.
  update public.items_tracker_items
  set
    updated_by = auth.uid(),
    updated_by_role = v_role
  where id = p_item_id;

  return v_comment;
end;
$$;

create or replace function public.item_tracker_register_attachment(
  p_item_id uuid,
  p_storage_path text,
  p_file_name text,
  p_mime_type text,
  p_file_size bigint
)
returns public.items_tracker_attachments
language plpgsql
security definer
set search_path = pg_catalog, public, storage
as $$
declare
  v_role text := public.item_tracker_my_role();
  v_event public.items_tracker_events%rowtype;
  v_attachment public.items_tracker_attachments%rowtype;
  v_expected_prefix text;
  v_activity_event_id bigint;
  v_activity_actor_id uuid;
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  if nullif(btrim(coalesce(p_file_name, '')), '') is null then
    raise exception 'ATTACHMENT_FILE_NAME_REQUIRED'
      using errcode = '22023';
  end if;

  if p_mime_type not in (
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp'
  ) then
    raise exception 'ATTACHMENT_TYPE_NOT_ALLOWED'
      using errcode = '22023';
  end if;

  if p_file_size is null or p_file_size <= 0 or p_file_size > 15728640 then
    raise exception 'ATTACHMENT_SIZE_NOT_ALLOWED'
      using errcode = '22023';
  end if;

  perform 1 from public.items_tracker_items where id = p_item_id for update;

  if not found then
    raise exception 'ITEMS_TRACKER_ITEM_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  select e.id, e.actor_id
  into v_activity_event_id, v_activity_actor_id
  from public.items_tracker_events e
  where e.item_id = p_item_id
    and e.event_type in ('action', 'follow_up')
  order by e.created_at desc, e.id desc
  limit 1;

  if v_activity_event_id is null or v_activity_actor_id <> auth.uid() then
    raise exception 'ATTACHMENT_REQUIRES_YOUR_LATEST_ACTIVITY'
      using errcode = '42501';
  end if;

  v_expected_prefix := p_item_id::text || '/' || auth.uid()::text || '/';
  if p_storage_path is null
    or left(p_storage_path, length(v_expected_prefix)) <> v_expected_prefix then
    raise exception 'INVALID_ATTACHMENT_STORAGE_PATH'
      using errcode = '22023';
  end if;

  perform 1
  from storage.objects o
  where o.bucket_id = 'items-tracker-files'
    and o.name = p_storage_path
    and coalesce(o.owner_id::text, '') = auth.uid()::text;

  if not found then
    raise exception 'ATTACHMENT_OBJECT_NOT_FOUND_OR_NOT_OWNED'
      using errcode = '42501';
  end if;

  insert into public.items_tracker_events (
    item_id,
    event_type,
    body,
    details,
    actor_id,
    actor_role
  ) values (
    p_item_id,
    'file_uploaded',
    'Uploaded file: ' || btrim(p_file_name),
    jsonb_build_object(
      'file_name', btrim(p_file_name),
      'mime_type', p_mime_type,
      'file_size', p_file_size,
      'storage_path', p_storage_path
    ),
    auth.uid(),
    v_role
  )
  returning * into v_event;

  insert into public.items_tracker_attachments (
    item_id,
    event_id,
    activity_event_id,
    bucket_name,
    storage_path,
    file_name,
    mime_type,
    file_size,
    created_by,
    created_by_role
  ) values (
    p_item_id,
    v_event.id,
    v_activity_event_id,
    'items-tracker-files',
    p_storage_path,
    btrim(p_file_name),
    p_mime_type,
    p_file_size,
    auth.uid(),
    v_role
  )
  returning * into v_attachment;

  update public.items_tracker_items
  set
    updated_by = auth.uid(),
    updated_by_role = v_role
  where id = p_item_id;

  return v_attachment;
end;
$$;

create or replace function public.item_tracker_actor_name(p_user_id uuid)
returns text
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  return (
    select nullif(btrim(u.user_name), '')
    from public.app_users u
    where u.user_id = p_user_id
    limit 1
  );
end;
$$;

drop function if exists public.item_tracker_fetch_timeline(uuid);
create function public.item_tracker_fetch_timeline(
  p_item_id uuid
)
returns table (
  id bigint,
  entry_type text,
  event_type text,
  body text,
  action_date date,
  from_follow_up_role text,
  to_follow_up_role text,
  from_case_status text,
  to_case_status text,
  actor_id uuid,
  actor_role text,
  actor_name text,
  details jsonb,
  created_at timestamptz,
  attachment_id uuid,
  storage_path text,
  file_name text,
  mime_type text,
  file_size bigint
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
begin
  if v_role is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED'
      using errcode = '42501';
  end if;

  perform 1
  from public.items_tracker_items i
  where i.id = p_item_id;

  if not found then
    raise exception 'ITEMS_TRACKER_ITEM_NOT_FOUND'
      using errcode = 'P0002';
  end if;

  return query
  select timeline.*
  from (
    select
      e.id,
      'event'::text as entry_type,
      e.event_type,
      e.body,
      e.action_date,
      e.from_follow_up_role,
      e.to_follow_up_role,
      e.from_case_status,
      e.to_case_status,
      e.actor_id,
      e.actor_role,
      public.item_tracker_actor_name(e.actor_id) as actor_name,
      e.details,
      e.created_at,
      a.id as attachment_id,
      a.storage_path,
      a.file_name,
      a.mime_type,
      a.file_size
    from public.items_tracker_events e
    left join public.items_tracker_attachments a
      on a.event_id = e.id
    where e.item_id = p_item_id

    union all

    select
      c.id,
      'comment'::text as entry_type,
      'comment'::text as event_type,
      c.body,
      null::date as action_date,
      null::text as from_follow_up_role,
      null::text as to_follow_up_role,
      null::text as from_case_status,
      null::text as to_case_status,
      c.created_by as actor_id,
      c.created_by_role as actor_role,
      public.item_tracker_actor_name(c.created_by) as actor_name,
      '{}'::jsonb as details,
      c.created_at,
      null::uuid as attachment_id,
      null::text as storage_path,
      null::text as file_name,
      null::text as mime_type,
      null::bigint as file_size
    from public.items_tracker_comments c
    where c.item_id = p_item_id
  ) timeline
  order by timeline.created_at desc, timeline.id desc;
end;
$$;

-- The view contains both dedicated last-action/follow-up columns and the latest
-- activity across those two streams. Ordering is by the server insertion time,
-- while action_date remains the department-entered business date.
drop view if exists public.item_tracker_grid;
create view public.item_tracker_grid
with (security_invoker = true)
as
select
  i.*,
  public.item_tracker_my_role() as viewer_role,
  (i.follow_up_role = public.item_tracker_my_role()) as is_my_follow_up,
  case
    when i.follow_up_role = public.item_tracker_my_role() then 0
    else 1
  end as assignment_priority,

  last_action.id as last_action_id,
  last_action.body as last_action,
  last_action.action_date as last_action_date,
  last_action.created_at as last_action_added_at,
  last_action.actor_role as last_action_by_role,
  public.item_tracker_actor_name(last_action.actor_id) as last_action_by_name,

  last_follow_up.id as last_follow_up_event_id,
  last_follow_up.from_follow_up_role,
  last_follow_up.to_follow_up_role as last_follow_up_role,
  last_follow_up.body as last_follow_up_note,
  last_follow_up.action_date as last_follow_up_date,
  last_follow_up.created_at as last_follow_up_at,
  last_follow_up.created_at as last_follow_up_added_at,
  last_follow_up.actor_role as last_follow_up_by_role,
  public.item_tracker_actor_name(last_follow_up.actor_id) as last_follow_up_by_name,

  latest_activity.id as latest_activity_id,
  latest_activity.event_type as latest_activity_type,
  case
    when latest_activity.event_type = 'action'
      then latest_activity.body
    else coalesce(
      nullif(btrim(latest_activity.body), ''),
      concat(
        'Follow-up: ',
        coalesce(latest_activity.from_follow_up_role, 'Created'),
        ' -> ',
        latest_activity.to_follow_up_role
      )
    )
  end as latest_activity,
  coalesce(
    latest_activity.action_date,
    (latest_activity.created_at at time zone 'Asia/Dubai')::date
  ) as latest_activity_date,
  latest_activity.created_at as latest_activity_added_at,
  latest_activity.actor_role as latest_activity_by_role,
  public.item_tracker_actor_name(latest_activity.actor_id) as latest_activity_by_name,
  latest_attachment.id as latest_activity_attachment_id,
  latest_attachment.storage_path as latest_activity_attachment_path,
  latest_attachment.file_name as latest_activity_attachment_name,
  latest_attachment.mime_type as latest_activity_attachment_mime_type,
  latest_attachment.file_size as latest_activity_attachment_size,

  last_comment.id as last_comment_id,
  last_comment.body as last_comment,
  last_comment.created_by_role as comment_by_role,
  public.item_tracker_actor_name(last_comment.created_by) as comment_by_name,
  last_comment.created_at as last_comment_at,
  coalesce(comment_totals.comment_count, 0::bigint) as comment_count
from public.items_tracker_items i
left join lateral (
  select e.*
  from public.items_tracker_events e
  where e.item_id = i.id
    and e.event_type = 'action'
  order by e.created_at desc, e.id desc
  limit 1
) last_action on true
left join lateral (
  select e.*
  from public.items_tracker_events e
  where e.item_id = i.id
    and e.event_type in ('created', 'follow_up')
  order by e.created_at desc, e.id desc
  limit 1
) last_follow_up on true
left join lateral (
  select e.*
  from public.items_tracker_events e
  where e.item_id = i.id
    and e.event_type in ('follow_up', 'action')
  order by e.created_at desc, e.id desc
  limit 1
) latest_activity on true
left join lateral (
  select a.*
  from public.items_tracker_attachments a
  where a.activity_event_id = latest_activity.id
  order by a.created_at desc, a.id desc
  limit 1
) latest_attachment on true
left join lateral (
  select c.*
  from public.items_tracker_comments c
  where c.item_id = i.id
  order by c.created_at desc, c.id desc
  limit 1
) last_comment on true
left join lateral (
  select count(*)::bigint as comment_count
  from public.items_tracker_comments c
  where c.item_id = i.id
) comment_totals on true;

alter table public.items_tracker_items enable row level security;
alter table public.items_tracker_events enable row level security;
alter table public.items_tracker_comments enable row level security;
alter table public.items_tracker_attachments enable row level security;

drop policy if exists items_tracker_attachments_select
  on public.items_tracker_attachments;
create policy items_tracker_attachments_select
on public.items_tracker_attachments
for select
to authenticated
using (public.item_tracker_my_role() is not null);

drop policy if exists items_tracker_storage_select
  on storage.objects;
create policy items_tracker_storage_select
on storage.objects
for select
to authenticated
using (
  bucket_id = 'items-tracker-files'
  and public.item_tracker_my_role() is not null
);

drop policy if exists items_tracker_storage_insert
  on storage.objects;
create policy items_tracker_storage_insert
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'items-tracker-files'
  and public.item_tracker_my_role() is not null
  and (storage.foldername(name))[2] = auth.uid()::text
  and exists (
    select 1
    from public.items_tracker_events e
    where e.id = (
      select latest_e.id
      from public.items_tracker_events latest_e
      where latest_e.item_id::text = (storage.foldername(name))[1]
        and latest_e.event_type in ('action', 'follow_up')
      order by latest_e.created_at desc, latest_e.id desc
      limit 1
    )
      and e.actor_id = auth.uid()
  )
);

drop policy if exists items_tracker_storage_delete_own
  on storage.objects;
create policy items_tracker_storage_delete_own
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'items-tracker-files'
  and public.item_tracker_my_role() is not null
  and (storage.foldername(name))[2] = auth.uid()::text
);

drop policy if exists items_tracker_items_select
  on public.items_tracker_items;
create policy items_tracker_items_select
on public.items_tracker_items
for select
to authenticated
using (public.item_tracker_my_role() is not null);

drop policy if exists items_tracker_events_select
  on public.items_tracker_events;
create policy items_tracker_events_select
on public.items_tracker_events
for select
to authenticated
using (public.item_tracker_my_role() is not null);

drop policy if exists items_tracker_comments_select
  on public.items_tracker_comments;
create policy items_tracker_comments_select
on public.items_tracker_comments
for select
to authenticated
using (public.item_tracker_my_role() is not null);

-- No direct write policy is intentional. Column ownership and assignment rules
-- cannot be secured with a broad UPDATE policy; every mutation goes through an
-- authorization-checking SECURITY DEFINER RPC above.
revoke all on table public.items_tracker_items
  from anon, authenticated;
revoke all on table public.items_tracker_events
  from anon, authenticated;
revoke all on table public.items_tracker_comments
  from anon, authenticated;
revoke all on table public.item_tracker_grid
  from anon, authenticated;

grant select on table public.items_tracker_items to authenticated;
grant select on table public.items_tracker_events to authenticated;
grant select on table public.items_tracker_comments to authenticated;
grant select on table public.items_tracker_attachments to authenticated;
grant select on table public.item_tracker_grid to authenticated;

grant all on table public.items_tracker_items to service_role;
grant all on table public.items_tracker_events to service_role;
grant all on table public.items_tracker_comments to service_role;
grant all on table public.items_tracker_attachments to service_role;
grant usage, select on sequence public.items_tracker_events_id_seq
  to service_role;
grant usage, select on sequence public.items_tracker_comments_id_seq
  to service_role;

revoke all on function public.item_tracker_my_role()
  from public, anon, authenticated;
revoke all on function public.item_tracker_actor_name(uuid)
  from public, anon, authenticated;
revoke all on function public.item_tracker_search_catalog(text, integer)
  from public, anon, authenticated;
revoke all on function public.item_tracker_status_options()
  from public, anon, authenticated;
revoke all on function public.item_tracker_create(
  date, text, numeric, text, numeric, text, text
) from public, anon, authenticated;
revoke all on function public.item_tracker_update_inventory_fields(
  uuid, date, numeric, text, numeric, text, text, bigint
) from public, anon, authenticated;
revoke all on function public.item_tracker_change_follow_up(
  uuid, text, text, date, bigint
)
  from public, anon, authenticated;
revoke all on function public.item_tracker_add_action(
  uuid, date, text, text, bigint
)
  from public, anon, authenticated;
revoke all on function public.item_tracker_update_tracker_status(
  uuid, text, bigint
) from public, anon, authenticated;
revoke all on function public.item_tracker_add_comment(uuid, text)
  from public, anon, authenticated;
revoke all on function public.item_tracker_register_attachment(
  uuid, text, text, text, bigint
) from public, anon, authenticated;
revoke all on function public.item_tracker_fetch_timeline(uuid)
  from public, anon, authenticated;

grant execute on function public.item_tracker_my_role()
  to authenticated;
grant execute on function public.item_tracker_actor_name(uuid)
  to authenticated;
grant execute on function public.item_tracker_search_catalog(text, integer)
  to authenticated;
grant execute on function public.item_tracker_status_options()
  to authenticated;
grant execute on function public.item_tracker_create(
  date, text, numeric, text, numeric, text, text
) to authenticated;
grant execute on function public.item_tracker_update_inventory_fields(
  uuid, date, numeric, text, numeric, text, text, bigint
) to authenticated;
grant execute on function public.item_tracker_change_follow_up(
  uuid, text, text, date, bigint
)
  to authenticated;
grant execute on function public.item_tracker_add_action(
  uuid, date, text, text, bigint
)
  to authenticated;
grant execute on function public.item_tracker_update_tracker_status(
  uuid, text, bigint
) to authenticated;
grant execute on function public.item_tracker_add_comment(uuid, text)
  to authenticated;
grant execute on function public.item_tracker_register_attachment(
  uuid, text, text, text, bigint
) to authenticated;
grant execute on function public.item_tracker_fetch_timeline(uuid)
  to authenticated;

-- Realtime is optional. The guarded block does nothing when the publication is
-- unavailable or the migration runner cannot alter it.
do $$
declare
  v_table text;
begin
  if exists (
    select 1
    from pg_catalog.pg_publication
    where pubname = 'supabase_realtime'
  ) then
    foreach v_table in array array[
      'items_tracker_items',
      'items_tracker_events',
      'items_tracker_comments',
      'items_tracker_attachments'
    ]
    loop
      begin
        if not exists (
          select 1
          from pg_catalog.pg_publication_tables
          where pubname = 'supabase_realtime'
            and schemaname = 'public'
            and tablename = v_table
        ) then
          execute format(
            'alter publication supabase_realtime add table public.%I',
            v_table
          );
        end if;
      exception
        when duplicate_object or insufficient_privilege or undefined_object
          then null;
      end;
    end loop;
  end if;
end;
$$;

comment on table public.items_tracker_items is
  'Current Items Tracker case state and immutable item_report snapshots.';
comment on table public.items_tracker_events is
  'Append-only audit timeline for creation, Inventory edits, actions, and follow-up transfers.';
comment on table public.items_tracker_comments is
  'Append-only comments visible and writable through RPC by all Items Tracker roles.';
comment on table public.items_tracker_attachments is
  'Private PDF/image metadata linked to immutable file-upload timeline events.';
comment on column public.items_tracker_items.retail_snapshot is
  'Reference retail copied from item_report; never used as unit cost.';
comment on column public.items_tracker_items.unit_cost_snapshot is
  'Optional unit cost entered manually by Inventory.';
comment on column public.items_tracker_events.action_date is
  'Business date selected by the department; created_at is the immutable server audit time.';

commit;
