-- Missing items report snapshot imported from Proactive ERP.

create table if not exists public.missing_items (
  id bigint generated by default as identity primary key,
  report_date date not null,
  warehouse text,
  sales_man text,
  item_code text,
  item_name text,
  barcode text,
  description text,
  request_type text,
  action_needed text,
  required_quantity numeric,
  added_date timestamptz,
  added_user_name text,
  notes text,
  synced_at timestamptz not null default now()
);

create index if not exists missing_items_report_date_idx
  on public.missing_items (report_date desc);

create index if not exists missing_items_item_code_idx
  on public.missing_items (item_code);

create index if not exists missing_items_added_date_idx
  on public.missing_items (added_date desc);

alter table public.missing_items enable row level security;

drop policy if exists "Authenticated users can read missing items"
  on public.missing_items;

create policy "Authenticated users can read missing items"
  on public.missing_items
  for select
  to authenticated
  using (true);

revoke all on table public.missing_items from anon;
grant select on table public.missing_items to authenticated;
grant all on table public.missing_items to service_role;
grant usage, select on sequence public.missing_items_id_seq to service_role;

-- Replace one report date inside a single transaction. This prevents partial
-- data when the scheduled script is rerun or an upload fails.
create or replace function public.replace_missing_items(
  p_report_date date,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer := 0;
begin
  if p_report_date is null then
    raise exception 'p_report_date is required';
  end if;

  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    raise exception 'p_rows must be a JSON array';
  end if;

  delete from public.missing_items
  where report_date = p_report_date;

  insert into public.missing_items (
    report_date,
    warehouse,
    sales_man,
    item_code,
    item_name,
    barcode,
    description,
    request_type,
    action_needed,
    required_quantity,
    added_date,
    added_user_name,
    notes
  )
  select
    p_report_date,
    nullif(btrim(row_data.warehouse), ''),
    nullif(btrim(row_data.sales_man), ''),
    nullif(btrim(row_data.item_code), ''),
    nullif(btrim(row_data.item_name), ''),
    nullif(btrim(row_data.barcode), ''),
    nullif(btrim(row_data.description), ''),
    nullif(btrim(row_data.request_type), ''),
    nullif(btrim(row_data.action_needed), ''),
    nullif(btrim(row_data.required_quantity), '')::numeric,
    nullif(btrim(row_data.added_date), '')::timestamptz,
    nullif(btrim(row_data.added_user_name), ''),
    nullif(btrim(row_data.notes), '')
  from jsonb_to_recordset(p_rows) as row_data (
    warehouse text,
    sales_man text,
    item_code text,
    item_name text,
    barcode text,
    description text,
    request_type text,
    action_needed text,
    required_quantity text,
    added_date text,
    added_user_name text,
    notes text
  );

  get diagnostics inserted_count = row_count;
  return inserted_count;
end;
$$;

revoke all on function public.replace_missing_items(date, jsonb) from public;
revoke all on function public.replace_missing_items(date, jsonb) from anon;
revoke all on function public.replace_missing_items(date, jsonb) from authenticated;
grant execute on function public.replace_missing_items(date, jsonb)
  to service_role;

comment on table public.missing_items is
  'Daily POS item-not-found requests imported from Proactive ERP.';

comment on column public.missing_items.report_date is
  'Date used in both ERP report filters; defaults to yesterday in Asia/Dubai.';
