-- Purchase Status module
-- Run once in the Supabase SQL editor, then assign app_users.role = 'purchase'.

begin;

-- Some installations use this conventional check constraint for app roles.
-- Removing it lets the new Purchase role be assigned without changing existing roles.
alter table if exists public.app_users
  drop constraint if exists app_users_role_check;

create table if not exists public.purchase_status_options (
  id bigint generated by default as identity primary key,
  name text not null,
  is_active boolean not null default true,
  display_order integer not null default 100,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  constraint purchase_status_options_name_not_blank check (btrim(name) <> '')
);

create unique index if not exists purchase_status_options_name_unique
  on public.purchase_status_options (lower(btrim(name)));

create table if not exists public.purchase_status_items (
  id bigint generated by default as identity primary key,
  item_code text,
  item_name text not null,
  status_id bigint not null references public.purchase_status_options(id),
  status_date date not null default current_date,
  alternative_item_code text,
  alternative_item_name text,
  note text,
  purchase_status text,
  category text,
  supplier text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  updated_at timestamptz not null default now(),
  updated_by uuid default auth.uid(),
  constraint purchase_status_items_item_code_unique unique (item_code),
  constraint purchase_status_items_item_name_not_blank check (btrim(item_name) <> '')
);

create index if not exists purchase_status_items_status_id_idx
  on public.purchase_status_items(status_id);
create index if not exists purchase_status_items_status_date_idx
  on public.purchase_status_items(status_date desc);
create index if not exists purchase_status_items_updated_at_idx
  on public.purchase_status_items(updated_at desc, id desc);
create index if not exists purchase_status_items_item_name_idx
  on public.purchase_status_items(lower(item_name));

create table if not exists public.purchase_status_items_log (
  id bigint generated by default as identity primary key,
  record_id bigint not null,
  operation text not null check (operation in ('UPDATE', 'DELETE')),
  item_code text,
  item_name text not null,
  status_id bigint,
  status_name text,
  status_date date not null,
  alternative_item_code text,
  alternative_item_name text,
  note text,
  purchase_status text,
  category text,
  supplier text,
  original_created_at timestamptz,
  original_created_by uuid,
  original_updated_at timestamptz,
  original_updated_by uuid,
  changed_at timestamptz not null default now(),
  changed_by uuid default auth.uid()
);

-- Keep reruns compatible with installations created by an older version.
alter table public.purchase_status_items
  alter column item_code drop not null;
alter table public.purchase_status_items
  drop constraint if exists purchase_status_items_item_code_not_blank;
alter table public.purchase_status_items_log
  alter column item_code drop not null;

create index if not exists purchase_status_items_log_record_id_idx
  on public.purchase_status_items_log(record_id, changed_at desc);

create or replace function public.is_purchase_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.app_users
    where user_id = auth.uid()
      and is_active is not false
      and lower(btrim(role::text)) = 'purchase'
  );
$$;

create or replace function public.audit_purchase_status_item()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  old_status_name text;
begin
  select name into old_status_name
  from public.purchase_status_options
  where id = old.status_id;

  insert into public.purchase_status_items_log (
    record_id, operation, item_code, item_name, status_id, status_name,
    status_date, alternative_item_code, alternative_item_name, note,
    purchase_status, category, supplier,
    original_created_at, original_created_by,
    original_updated_at, original_updated_by, changed_by
  ) values (
    old.id, tg_op, old.item_code, old.item_name, old.status_id, old_status_name,
    old.status_date, old.alternative_item_code, old.alternative_item_name, old.note,
    old.purchase_status, old.category, old.supplier,
    old.created_at, old.created_by,
    old.updated_at, old.updated_by, auth.uid()
  );

  if tg_op = 'UPDATE' then
    new.updated_at := now();
    new.updated_by := coalesce(auth.uid(), new.updated_by);
    return new;
  end if;
  return old;
end;
$$;

drop trigger if exists purchase_status_items_audit_trigger
  on public.purchase_status_items;
create trigger purchase_status_items_audit_trigger
before update or delete on public.purchase_status_items
for each row execute function public.audit_purchase_status_item();

insert into public.purchase_status_options (name, display_order)
values
  ('Out Of Stock - Alternative', 10),
  ('Out Of Stock - No Alternative', 20),
  ('AVAILABLE', 30),
  ('AVAILABLE N.E', 40),
  ('NOT AVAILABLE', 50),
  ('BACK TO STOCK', 60),
  ('DISCONTINUED', 70),
  ('PENDING AGREEMENT', 80),
  ('ASSIGNED TO CATEGORY', 90),
  ('ALLOCATE', 100),
  ('LIQUIDATION', 110),
  ('AVAILABLE N.E. - EXPIRY 07/2026', 120),
  ('OOS', 130),
  ('PLACED FOR GROUP', 140),
  ('ASSIGNED TO INVENTORY', 150)
on conflict do nothing;

alter table public.purchase_status_options enable row level security;
alter table public.purchase_status_items enable row level security;
alter table public.purchase_status_items_log enable row level security;

drop policy if exists purchase_status_options_select on public.purchase_status_options;
create policy purchase_status_options_select
on public.purchase_status_options for select
to authenticated using (public.is_purchase_user());

drop policy if exists purchase_status_options_insert on public.purchase_status_options;
create policy purchase_status_options_insert
on public.purchase_status_options for insert
to authenticated with check (public.is_purchase_user());

drop policy if exists purchase_status_options_update on public.purchase_status_options;
create policy purchase_status_options_update
on public.purchase_status_options for update
to authenticated using (public.is_purchase_user()) with check (public.is_purchase_user());

drop policy if exists purchase_status_items_select on public.purchase_status_items;
create policy purchase_status_items_select
on public.purchase_status_items for select
to authenticated using (public.is_purchase_user());

drop policy if exists purchase_status_items_insert on public.purchase_status_items;
create policy purchase_status_items_insert
on public.purchase_status_items for insert
to authenticated with check (public.is_purchase_user());

drop policy if exists purchase_status_items_update on public.purchase_status_items;
create policy purchase_status_items_update
on public.purchase_status_items for update
to authenticated using (public.is_purchase_user()) with check (public.is_purchase_user());

drop policy if exists purchase_status_items_delete on public.purchase_status_items;
create policy purchase_status_items_delete
on public.purchase_status_items for delete
to authenticated using (public.is_purchase_user());

drop policy if exists purchase_status_items_log_select on public.purchase_status_items_log;
create policy purchase_status_items_log_select
on public.purchase_status_items_log for select
to authenticated using (public.is_purchase_user());

grant select, insert, update on public.purchase_status_options to authenticated;
grant select, insert, update, delete on public.purchase_status_items to authenticated;
grant select on public.purchase_status_items_log to authenticated;
grant usage, select on sequence public.purchase_status_options_id_seq to authenticated;
grant usage, select on sequence public.purchase_status_items_id_seq to authenticated;
grant execute on function public.is_purchase_user() to authenticated;

commit;

-- Example (replace values):
-- update public.app_users
-- set role = 'purchase', branch_name = null
-- where user_id = '00000000-0000-0000-0000-000000000000';
