enum InventoryPageType {
  dashboard,
  mismatch,
  maxAdjustment,
  formulary,
  assortment,
  dailyOrder,
  tma,
  additionalOrders,

  additionalOrderAnalysis,
  orderEditAnalysis,
  branchSubmissionTracker,
  branchesTracker,
  allocation,
  stockCheck,
  shortage,
  availabilityKpi,
  branchSetting,
}
