-- Personal, persistent notifications for Items Tracker collaboration.
-- A notification is created for every active tracker user except the actor.
-- Read state is intentionally per user, never per department.

begin;

create table public.items_tracker_notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  item_id uuid not null references public.items_tracker_items(id) on delete cascade,
  activity_type text not null,
  actor_id uuid not null,
  actor_role text not null,
  actor_name text,
  item_code text not null,
  item_name text not null,
  title text not null,
  preview text,
  created_at timestamptz not null default now(),
  read_at timestamptz,

  constraint items_tracker_notifications_activity_type_check check (
    activity_type in (
      'created', 'inventory_update', 'action', 'follow_up',
      'status_change', 'file_uploaded', 'comment'
    )
  ),
  constraint items_tracker_notifications_actor_role_check check (
    actor_role in ('inventory', 'purchase', 'category')
  ),
  constraint items_tracker_notifications_title_not_blank
    check (btrim(title) <> '')
);

create index items_tracker_notifications_recipient_unread_idx
  on public.items_tracker_notifications (recipient_id, created_at desc)
  where read_at is null;
create index items_tracker_notifications_recipient_created_idx
  on public.items_tracker_notifications (recipient_id, created_at desc);
create index items_tracker_notifications_item_idx
  on public.items_tracker_notifications (item_id, created_at desc);

create or replace function public.item_tracker_notification_label(
  p_activity_type text
)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select case p_activity_type
    when 'created' then 'added a new item'
    when 'inventory_update' then 'updated item details'
    when 'action' then 'added an action'
    when 'follow_up' then 'updated the follow-up'
    when 'status_change' then 'changed the tracker status'
    when 'file_uploaded' then 'uploaded a file'
    when 'comment' then 'added a comment'
    else 'updated the item'
  end;
$$;

create or replace function public.item_tracker_create_notifications()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_item public.items_tracker_items%rowtype;
  v_activity_type text;
  v_actor_id uuid;
  v_actor_role text;
  v_actor_name text;
  v_preview text;
  v_label text;
begin
  if tg_table_name = 'items_tracker_comments' then
    v_activity_type := 'comment';
    v_actor_id := new.created_by;
    v_actor_role := new.created_by_role;
    v_preview := nullif(btrim(new.body), '');
  else
    v_activity_type := new.event_type;
    v_actor_id := new.actor_id;
    v_actor_role := new.actor_role;
    v_preview := nullif(btrim(new.body), '');
  end if;

  select * into v_item
  from public.items_tracker_items
  where id = new.item_id;

  if not found then
    return new;
  end if;

  select nullif(btrim(user_name), '') into v_actor_name
  from public.app_users
  where user_id = v_actor_id;

  v_actor_name := coalesce(v_actor_name, initcap(v_actor_role));
  v_label := public.item_tracker_notification_label(v_activity_type);

  insert into public.items_tracker_notifications (
    recipient_id, item_id, activity_type, actor_id, actor_role, actor_name,
    item_code, item_name, title, preview
  )
  select
    u.user_id,
    v_item.id,
    v_activity_type,
    v_actor_id,
    v_actor_role,
    v_actor_name,
    v_item.item_code,
    v_item.item_name,
    v_actor_name || ' ' || v_label,
    v_preview
  from public.app_users u
  where u.is_active is not false
    and lower(btrim(u.role::text)) in ('inventory', 'purchase', 'category')
    and u.user_id <> v_actor_id;

  return new;
end;
$$;

drop trigger if exists items_tracker_notifications_from_events
  on public.items_tracker_events;
create trigger items_tracker_notifications_from_events
after insert on public.items_tracker_events
for each row execute function public.item_tracker_create_notifications();

drop trigger if exists items_tracker_notifications_from_comments
  on public.items_tracker_comments;
create trigger items_tracker_notifications_from_comments
after insert on public.items_tracker_comments
for each row execute function public.item_tracker_create_notifications();

create or replace function public.item_tracker_fetch_notifications(
  p_limit integer default 50
)
returns table (
  id bigint,
  item_id uuid,
  activity_type text,
  actor_name text,
  actor_role text,
  item_code text,
  item_name text,
  title text,
  preview text,
  created_at timestamptz,
  read_at timestamptz
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  v_role text := public.item_tracker_my_role();
begin
  if v_role is null or auth.uid() is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED' using errcode = '42501';
  end if;

  return query
  select
    n.id, n.item_id, n.activity_type, n.actor_name, n.actor_role,
    n.item_code, n.item_name, n.title, n.preview, n.created_at, n.read_at
  from public.items_tracker_notifications n
  where n.recipient_id = auth.uid()
  order by n.created_at desc, n.id desc
  limit greatest(1, least(coalesce(p_limit, 50), 100));
end;
$$;

create or replace function public.item_tracker_mark_notification_read(
  p_notification_id bigint
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if public.item_tracker_my_role() is null or auth.uid() is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED' using errcode = '42501';
  end if;

  update public.items_tracker_notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id
    and recipient_id = auth.uid();
end;
$$;

create or replace function public.item_tracker_mark_all_notifications_read()
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if public.item_tracker_my_role() is null or auth.uid() is null then
    raise exception 'ITEMS_TRACKER_PERMISSION_REQUIRED' using errcode = '42501';
  end if;

  update public.items_tracker_notifications
  set read_at = now()
  where recipient_id = auth.uid()
    and read_at is null;
end;
$$;

alter table public.items_tracker_notifications enable row level security;

create policy items_tracker_notifications_select_own
on public.items_tracker_notifications
for select
to authenticated
using (recipient_id = (select auth.uid()));

revoke all on table public.items_tracker_notifications
  from anon, authenticated;
grant select on table public.items_tracker_notifications to authenticated;
grant all on table public.items_tracker_notifications to service_role;
grant usage, select on sequence public.items_tracker_notifications_id_seq
  to service_role;

revoke all on function public.item_tracker_notification_label(text)
  from public, anon, authenticated;
revoke all on function public.item_tracker_create_notifications()
  from public, anon, authenticated;
revoke all on function public.item_tracker_fetch_notifications(integer)
  from public, anon, authenticated;
revoke all on function public.item_tracker_mark_notification_read(bigint)
  from public, anon, authenticated;
revoke all on function public.item_tracker_mark_all_notifications_read()
  from public, anon, authenticated;
grant execute on function public.item_tracker_fetch_notifications(integer)
  to authenticated;
grant execute on function public.item_tracker_mark_notification_read(bigint)
  to authenticated;
grant execute on function public.item_tracker_mark_all_notifications_read()
  to authenticated;

-- Notifications refresh in real time; RLS ensures each user receives only
-- their own rows.
do $$
begin
  if exists (
    select 1 from pg_catalog.pg_publication where pubname = 'supabase_realtime'
  ) then
    begin
      if not exists (
        select 1 from pg_catalog.pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'items_tracker_notifications'
      ) then
        alter publication supabase_realtime
          add table public.items_tracker_notifications;
      end if;
    exception when duplicate_object or insufficient_privilege or undefined_object then null;
    end;
  end if;
end;
$$;

comment on table public.items_tracker_notifications is
  'Per-user Items Tracker activity notifications with a persistent read state.';

commit;
